package View;


import DomainModel.users;
import Service.IDangNhapService;
import Service.Impl.DangNhapService;
import View.Main;
import ViewModel.UsersViewModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author BOSS
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    private IDangNhapService dns;

    public DangNhap() {
        initComponents();

        this.dns = new DangNhapService();
        addIcon();
        setLocationRelativeTo(null);
    }

    public void addIcon() {
        Icon icon1 = new ImageIcon("img/Coolmate.png");
        lb_anh.setIcon(icon1);
        Icon icon2 = new ImageIcon("img/mau-be-vang.jpg");
        lb_dangnhap.setIcon(icon2);
        Icon icon3 = new ImageIcon("img/2.png");
        lbLogo.setIcon(icon3);
        Icon icon4 = new ImageIcon("img/user.png");
        lbMa.setIcon(icon4);
        Icon icon5 = new ImageIcon("img/padlock.png");
        lbMatkhau.setIcon(icon5);
        Icon icon6 = new ImageIcon("img/thoat.png");
        btn_dangNhap.setIcon(icon5);
        Icon icon7 = new ImageIcon("img/exit.png");
        btn_thoat.setIcon(icon5);
    }

    public users getForm() {
        String MaStr = txtMa.getText().trim();
        String matkh = matkhau.getText().trim();
        if (MaStr.length() == 0 || matkh.length() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            return null;
        }
        users u = this.dns.login(MaStr, matkh);
        return u;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_anh = new javax.swing.JLabel();
        lbMa = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        lbMatkhau = new javax.swing.JLabel();
        matkhau = new javax.swing.JPasswordField();
        btn_dangNhap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        btn_thoat = new javax.swing.JButton();
        lb_dangnhap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lb_anh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 500));

        lbMa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMa.setText("Mã Người dùng");
        getContentPane().add(lbMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));
        getContentPane().add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 200, -1));

        lbMatkhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMatkhau.setText("Mật khẩu");
        getContentPane().add(lbMatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));
        getContentPane().add(matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 200, -1));

        btn_dangNhap.setBackground(new java.awt.Color(255, 51, 51));
        btn_dangNhap.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_dangNhap.setText("Đăng nhập");
        btn_dangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 302, 350, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Quên mật khẩu ?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, -1, -1));
        getContentPane().add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 140, 80));

        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        getContentPane().add(btn_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, -1));
        getContentPane().add(lb_dangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 370, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void btn_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhapActionPerformed
        // TODO add your handling code here:
        users u = this.getForm();
        users account = dns.login(txtMa.getText().trim(), matkhau.getText().trim());
        if (account == null) {
            JOptionPane.showMessageDialog(this, "Sai tài khoản");
            return;
        } else {
            JOptionPane.showMessageDialog(this, "Thành công");
            if (u.getVaiTro() == 1) {
                Main m = new Main();
                m.setVisible(true);
            } else {

            }
        }
    }//GEN-LAST:event_btn_dangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangNhap;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbMa;
    private javax.swing.JLabel lbMatkhau;
    private javax.swing.JLabel lb_anh;
    private javax.swing.JLabel lb_dangnhap;
    private javax.swing.JPasswordField matkhau;
    private javax.swing.JTextField txtMa;
    // End of variables declaration//GEN-END:variables
}
